###

POST http://localhost:3001/auth/init
Content-Type: application/json

{
    "email":"student@nitw.ac.in"
}

###

POST http://localhost:3001/auth/token
Content-Type: application/json

{
    "userId":"50829cb9-d010-44ae-862a-166f6e54094a",
    "provider":"github",
    "accessToken":"ghp_fake_token_123456789"
}